services:
    php:
        build: .
        container_name: php-container
        restart: on-failure:5
        working_dir: /var/www/
        ports:
            - 9000:9000
        command: sh -c "composer install --no-interaction --prefer-dist && php-fpm"
        depends_on:
            - db
        volumes:
            - ./:/var/www
        networks:
            - web-network
            - db-network
    db:
        image: mariadb:10.5
        container_name: db-container
        restart: on-failure:5
        # command:
        #     --log-error=/var/log/mysql/error.log
        #     --general-log=1
        #     --general-log-file=/var/log/mysql/general.log
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 3306:3306
        volumes:
            - ./docker-compose/mariadb:/docker-entrypoint-initdb.d      # Pour les scripts d'initialisation
            - ./db:/var/lib/mysql                                       # Pour les données de la base de données
            # - ./docker-compose/mariadb/logs:/var/log/mysql
        networks:
            - pma-network
            - db-network

    nginx:
        image: nginx:alpine
        container_name: nginx-container
        restart: unless-stopped
        depends_on:
            - db
            - php
        ports:
            - 443:80
        volumes:
            - ./public:/var/www/public                            # Monté pour l'application web
            - ./docker-compose/nginx/gestion-stock.conf:/etc/nginx/conf.d/default.conf # Configuration de Nginx
            - ./docker-compose/nginx/logs:/var/log/nginx          # Pour les logs de Nginx
        networks:
            - web-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-container
        restart: unless-stopped
        depends_on:
            - db
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 8080:80
        networks:
            - pma-network

networks:
    web-network:
        driver: bridge
    pma-network:
        driver: bridge
    db-network:
        driver: bridge